### ISSUE TITLE
cronjobs no longer running

### ISSUE THREAD

**Issue by ghost** [nextcloud/helm#215] opened 2022-03-28 16:51 UTC
per this issue webcron isnt even supported but its in the docs and in this helm chart
https://github.com/nextcloud/server/issues/30899#issuecomment-1025430197

i have a warning in my ui that jobs have not run for days after upgrading to 23.0.3 using this official chart. using ajax never seemed to work for me and the system cron doesnt seem implemented in this container.

suggestions for running these jobs?

**Comment by LukasDJacobs** [comment] 2022-04-19 07:06
https://help.nextcloud.com/t/occ-wont-run-with-memcache-apcu/119724/14

See here, seems to be an issue with the configuration of php and the latest version of nextcloud. Would be greatly appreciated if this could be incorporated into the chart.

**Comment by SchoolGuy** [comment] 2022-09-05 21:39
The issue is fixed in the server repository and the documentation was updated. Thus this can maybe also be closed?

**Closed** 2022-10-25 16:39 UTC
